### ISSUE TITLE
Cannot clone succesfully into WordPress Boiler Plate repository

### ISSUE THREAD

**Issue by MasterMind92** [claudiosanches/wordpress-plugin-boilerplate#2]
Hey i won't long, just here is error i a getting while trying to clone that repository in the command line:
git clone git@github.com:claudiosmweb/wordpress-plugin-bootstrap.git

Cloning into 'wordpress-plugin-bootstrap'...

Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.

**git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.**

**Please make sure you have the correct access rights
and the repository exists.**

Got any idea ?

**Comment by claudiosanches** [comment]
This is outdated, but the correct link without permissions is https://github.com/claudiosanches/wordpress-plugin-boilerplate.git
